// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxZJa16O95kqUJ-I8eIJCUdBOdJIICfE',
    appId: '1:887223314586:web:b417c0e826da3c52bdd723',
    messagingSenderId: '887223314586',
    projectId: 'foocommers',
    authDomain: 'foocommers.firebaseapp.com',
    storageBucket: 'foocommers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL_mOug3IWceiRKq97RvQ9zaA9ks0WXvI',
    appId: '1:887223314586:android:c987890deb74871dbdd723',
    messagingSenderId: '887223314586',
    projectId: 'foocommers',
    storageBucket: 'foocommers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe4_cfslOQEVqZH4OPf8dkmnKs93WeSbc',
    appId: '1:887223314586:ios:8cbd8499fb2333afbdd723',
    messagingSenderId: '887223314586',
    projectId: 'foocommers',
    storageBucket: 'foocommers.appspot.com',
    iosClientId:
        '887223314586-5m2bit85psess5i6jdjhr57roal0bo30.apps.googleusercontent.com',
    iosBundleId: 'com.example.blankFireSetstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe4_cfslOQEVqZH4OPf8dkmnKs93WeSbc',
    appId: '1:887223314586:ios:8cbd8499fb2333afbdd723',
    messagingSenderId: '887223314586',
    projectId: 'foocommers',
    storageBucket: 'foocommers.appspot.com',
    iosClientId:
        '887223314586-5m2bit85psess5i6jdjhr57roal0bo30.apps.googleusercontent.com',
    iosBundleId: 'com.example.blankFireSetstate',
  );
}
